org: peleo
app: msg
service: msg

useDotenv: true

custom:
  settings:
    ACCOUNT_ID: "<Your Account ID>"

provider:
  name: aws
  runtime: nodejs14.x
  region: <Your Region>
  environment: ${self:custom.settings}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: "arn:aws:sqs:${self:provider.region}:${self:custom.settings.ACCOUNT_ID}:MyQueue"

functions:
  msg:
    handler: src/msg.handler
    events:
      - httpApi: Post /msg
  sqsHandler:
    handler: src/msg.sqsHandler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
          batchSize: 1

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MyQueue"

plugins:
  - serverless-esbuild
  - serverless-offline
