org: peleo
app: msg
service: msg

useDotenv: true

custom:
  settings:
    ACCOUNT_ID: "957429122486"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment: ${self:custom.settings}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: "arn:aws:sqs:${self:provider.region}:957429122486:MyQueue"

functions:
  msg:
    handler: src/msg.handler
    events:
      - httpApi: Post /msg
  sqsHandler:
    handler: src/msg.sqsHandler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
          batchSize: 1

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MyQueue"

plugins:
  - serverless-esbuild
  - serverless-offline
